name: BungeeVPN
version: '${project.version}'
main: io.github.jaceg18.bungeevpn.BungeeVPN
api-version: 1.19
authors: [ ftJace ]
description: Lightweight antivpn for bungee waterfall
commands:
  avpn:
    description: add or remove a player from ip-checking
    usage: /<command> <add/remove> <player>
    permission: bungeecord.avpn.command
    permission-message: Command requires bungeecord.avpn.command to execute
